version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            . ./bin/activate-hermit
            hermit install
            go install github.com/jstemmer/go-junit-report@latest
            go get -v -t -d ./...
            mkdir ~/report
          when: always
      - run:
          name: Lint
          command: |
            . ./bin/activate-hermit
            golangci-lint run
            (cd ./hil && golangci-lint run)
      - run:
          name: Test
          command: |
            . ./bin/activate-hermit
            (go test -v ./... && cd ./hil && go test -v ./...) 2>&1 | tee report.txt && go-junit-report < report.txt > ~/report/junit.xml
      - store_test_results:
          path: ~/report

